name: Run CodeceptJS Tests

# Chạy workflow này khi có lệnh push lên nhánh chính hoặc pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code từ GitHub repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Thiết lập Node.js môi trường
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Đảm bảo Node.js version phù hợp với dự án

    # Cài đặt các phụ thuộc
    - name: Install dependencies
      run: npm install

    # Cấp quyền thực thi cho CodeceptJS
    - name: Grant permission to CodeceptJS
      run: chmod +x ./node_modules/.bin/codeceptjs

      # Khởi động server (thay đổi lệnh này tùy thuộc vào cách khởi động server của bạn)
    - name: Start API server
      run: mvn spring-boot:run & # hoặc lệnh tương ứng để khởi động server

      # Chờ vài giây để server khởi động hoàn toàn
    - name: Wait for server to start
      run: sleep 10

    - name: Wait for server to be ready
      run: |
            n=0
            until [ $n -ge 30 ]
            do
              curl -s http://localhost:8080 && break
              n=$((n+1))
              echo "Waiting for server to start..."
              sleep 5
            done
      

      # Chạy test với CodeceptJS
    - name: Run CodeceptJS tests
      run: npx codeceptjs run --steps
